name: coach-pl

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda
  - lightning
  - tensorboard
  - pip
    - fvcore
    - omegaconf
