DATASET:
  NAME: null
  ROOT: null

  TRANSFORM:
    NAME: null

DATALOADER:
  BATCH_SIZE: 0
  NUM_WORKERS: 0
  PIN_MEMORY: False
  DROP_LAST: False
  PERSISTENT_WORKERS: False

MODEL:
  NAME: null
  DEVICE: cuda

  CRITERION:
    NAME: null
    TYPE: null

MODULE:
  NAME: null

  OPTIMIZER:
    NAME: null

  SCHEDULER:
    NAME: null

TRAINER:
  MIXED_PRECISION: False
  CHECKPOINT:
    EVERY_N_EPOCHS: 10

    SAVE_BEST: False    # If True, monitor will be required
    MONITOR: null

  MAX_EPOCHS: -1        # If profiler is enabled, this will be *automatically* set to 1
  LOG_EVERY_N_STEPS: 1
  ACCUMULATE_GRAD_BATCHES: 1

  CLIP_GRAD:
    ENABLED: False
    ALGORITHM: null
    VALUE: 0.0

  DETERMINISTIC: False  # Set to True to enable cudnn.deterministic
  BENCHMARK: False      # Set to True to enable cudnn.benchmark
  PROFILE: null         # Set to `advanced` or `pytorch` to enable profiling
  DETECT_ANOMALY: False # Set to True to enable anomaly detection
  SYNC_BATCHNORM: False # Set to True to enable sync batchnorm

SEED: null
OUTPUT_DIR: null
